<?php


namespace WebpageMNG;


use Exception;
use RoutesMNG\Parameters;

abstract class Page extends ContextCreator
{
    public bool $active;
    private ?Parameters $parameters;
    public function __construct(Parameters $parameters = null)
    {
        $this->parameters = $parameters;
        $this->active = false;
    }

   public function getParameters()
   {
       if($this->parameters === null && !empty($this->parameters))
           return $this->parameters;
       throw new Exception("Parameters doesn't initalize in this page");


   }


    abstract protected function pageContent();


    public function getContext()
    {
        $this->setActiveClass();
        $this->createPage();
        return parent::getContext(); // TODO: Change the autogenerated stub
    }
    public function createPage(): void
    {
        if ($this->active)
            $this->createContext();
    }

    protected function createContext() : void
    {
        $this->context = $this->pageContent();

    }

    public function setActiveClass()
    {
        $this->active = true;
    }

    public function isActive(){
        return $this->active;
    }
}


 abstract class ContextCreator
{
    //Tutaj nalezy sie zastanowic
    protected  $context;

    abstract protected function createContext();


    public function getContext()
    {
        return $this->context;
    }
}



